menus = {
    "ru": [
        "📖 Инструкция",
        "📊 Бюджет",
        "📚 База знаний",
        "🛠 Инструменты",
        "📎 Документы",
        "💰 Кошелёк",
        "📑 Лицензия",
        "🌐 Переводчик",
        "🤖 Инженер",
        "🎞 Генератор медиа",
        "⚙️ Настройки",
        "📞 Поддержка"
    ],
    "en": [
        "📖 Instruction",
        "📊 Budget",
        "📚 Knowledge Base",
        "🛠 Tools",
        "📎 Documents",
        "💰 Wallet",
        "📑 License",
        "🌐 Translator",
        "🤖 Engineer",
        "🎞 Media Generator",
        "⚙️ Settings",
        "📞 Support"
    ],
    "de": [
        "📖 Anleitung",
        "📊 Budget",
        "📚 Wissensbasis",
        "🛠 Werkzeuge",
        "📎 Dokumente",
        "💰 Geldbörse",
        "📑 Lizenz",
        "🌐 Übersetzer",
        "🤖 Ingenieur",
        "🎞 Mediengenerator",
        "⚙️ Einstellungen",
        "📞 Support"
    ],
    "pl": [
        "📖 Instrukcja",
        "📊 Budżet",
        "📚 Baza wiedzy",
        "🛠 Narzędzia",
        "📎 Dokumenty",
        "💰 Portfel",
        "📑 Licencja",
        "🌐 Tłumacz",
        "🤖 Inżynier",
        "🎞 Generator mediów",
        "⚙️ Ustawienia",
        "📞 Wsparcie"
    ],
    "fr": [
        "📖 Manuel",
        "📊 Budget",
        "📚 Base de connaissances",
        "🛠 Outils",
        "📎 Documents",
        "💰 Portefeuille",
        "📑 Licence",
        "🌐 Traducteur",
        "🤖 Ingénieur",
        "🎞 Générateur de médias",
        "⚙️ Paramètres",
        "📞 Support"
    ],
    "es": [
        "📖 Instrucción",
        "📊 Presupuesto",
        "📚 Base de conocimiento",
        "🛠 Herramientas",
        "📎 Documentos",
        "💰 Billetera",
        "📑 Licencia",
        "🌐 Traductor",
        "🤖 Ingeniero",
        "🎞 Generador de medios",
        "⚙️ Configuración",
        "📞 Soporte"
    ],
    "it": [
        "📖 Istruzione",
        "📊 Budget",
        "📚 Base di conoscenza",
        "🛠 Strumenti",
        "📎 Documenti",
        "💰 Portafoglio",
        "📑 Licenza",
        "🌐 Traduttore",
        "🤖 Ingegnere",
        "🎞 Generatore media",
        "⚙️ Impostazioni",
        "📞 Supporto"
    ],
    "ro": [
        "📖 Instrucțiune",
        "📊 Buget",
        "📚 Bază de cunoștințe",
        "🛠 Instrumente",
        "📎 Documente",
        "💰 Portofel",
        "📑 Licență",
        "🌐 Traducător",
        "🤖 Inginer",
        "🎞 Generator media",
        "⚙️ Setări",
        "📞 Suport"
    ],
    "bg": [
        "📖 Упътване",
        "📊 Бюджет",
        "📚 База знания",
        "🛠 Инструменти",
        "📎 Документи",
        "💰 Портфейл",
        "📑 Лиценз",
        "🌐 Преводач",
        "🤖 Инженер",
        "🎞 Медиен генератор",
        "⚙️ Настройки",
        "📞 Поддръжка"
    ],
    "lt": [
        "📖 Instrukcija",
        "📊 Biudžetas",
        "📚 Žinių bazė",
        "🛠 Įrankiai",
        "📎 Dokumentai",
        "💰 Piniginė",
        "📑 Licencija",
        "🌐 Vertėjas",
        "🤖 Inžinierius",
        "🎞 Medijos generatorius",
        "⚙️ Nustatymai",
        "📞 Pagalba"
    ],
    "lv": [
        "📖 Instrukcija",
        "📊 Budžets",
        "📚 Zināšanu bāze",
        "🛠 Rīki",
        "📎 Dokumenti",
        "💰 Maks",
        "📑 Licence",
        "🌐 Tulkotājs",
        "🤖 Inženieris",
        "🎞 Mediju ģenerators",
        "⚙️ Iestatījumi",
        "📞 Atbalsts"
    ],
    "et": [
        "📖 Juhend",
        "📊 Eelarve",
        "📚 Teadmistebaas",
        "🛠 Tööriistad",
        "📎 Dokumendid",
        "💰 Rahakott",
        "📑 Litsents",
        "🌐 Tõlkija",
        "🤖 Insener",
        "🎞 Meedia generaator",
        "⚙️ Seaded",
        "📞 Tugi"
    ],
    "hr": [
        "📖 Uputa",
        "📊 Proračun",
        "📚 Baza znanja",
        "🛠 Alati",
        "📎 Dokumenti",
        "💰 Novčanik",
        "📑 Licenca",
        "🌐 Prevoditelj",
        "🤖 Inženjer",
        "🎞 Generator medija",
        "⚙️ Postavke",
        "📞 Podrška"
    ],
    "hu": [
        "📖 Útmutató",
        "📊 Költségvetés",
        "📚 Tudásbázis",
        "🛠 Eszközök",
        "📎 Dokumentumok",
        "💰 Pénztárca",
        "📑 Licenc",
        "🌐 Fordító",
        "🤖 Mérnök",
        "🎞 Média generátor",
        "⚙️ Beállítások",
        "📞 Támogatás"
    ],
    "cs": [
        "📖 Návod",
        "📊 Rozpočet",
        "📚 Znalostní báze",
        "🛠 Nástroje",
        "📎 Dokumenty",
        "💰 Peněženka",
        "📑 Licence",
        "🌐 Překladač",
        "🤖 Inženýr",
        "🎞 Generátor médií",
        "⚙️ Nastavení",
        "📞 Podpora"
    ],
    "sk": [
        "📖 Pokyny",
        "📊 Rozpočet",
        "📚 Znalostná báza",
        "🛠 Nástroje",
        "📎 Dokumenty",
        "💰 Peňaženka",
        "📑 Licencia",
        "🌐 Prekladač",
        "🤖 Inžinier",
        "🎞 Generátor médií",
        "⚙️ Nastavenia",
        "📞 Podpora"
    ],
    "sl": [
        "📖 Navodila",
        "📊 Proračun",
        "📚 Baza znanja",
        "🛠 Orodja",
        "📎 Dokumenti",
        "💰 Denarnica",
        "📑 Licenca",
        "🌐 Prevajalnik",
        "🤖 Inženir",
        "🎞 Ustvarjalnik medijev",
        "⚙️ Nastavitve",
        "📞 Podpora"
    ],
    "pt": [
        "📖 Instrução",
        "📊 Orçamento",
        "📚 Base de conhecimento",
        "🛠 Ferramentas",
        "📎 Documentos",
        "💰 Carteira",
        "📑 Licença",
        "🌐 Tradutor",
        "🤖 Engenheiro",
        "🎞 Gerador de mídia",
        "⚙️ Configurações",
        "📞 Suporte"
    ],
    "el": [
        "📖 Οδηγός",
        "📊 Προϋπολογισμός",
        "📚 Βάση γνώσεων",
        "🛠 Εργαλεία",
        "📎 Έγγραφα",
        "💰 Πορτοφόλι",
        "📑 Άδεια",
        "🌐 Μεταφραστής",
        "🤖 Μηχανικός",
        "🎞 Δημιουργός πολυμέσων",
        "⚙️ Ρυθμίσεις",
        "📞 Υποστήριξη"
    ],
    "nl": [
        "📖 Instructie",
        "📊 Budget",
        "📚 Kennisbank",
        "🛠 Gereedschappen",
        "📎 Documenten",
        "💰 Portemonnee",
        "📑 Licentie",
        "🌐 Vertaler",
        "🤖 Ingenieur",
        "🎞 Mediagenerator",
        "⚙️ Instellingen",
        "📞 Ondersteuning"
    ],
    "da": [
        "📖 Instruktion",
        "📊 Budget",
        "📚 Vidensbase",
        "🛠 Værktøjer",
        "📎 Dokumenter",
        "💰 Tegnebog",
        "📑 Licens",
        "🌐 Oversætter",
        "🤖 Ingeniør",
        "🎞 Mediegenerator",
        "⚙️ Indstillinger",
        "📞 Support"
    ],
    "fi": [
        "📖 Ohjeet",
        "📊 Budjetti",
        "📚 Tietopohja",
        "🛠 Työkalut",
        "📎 Asiakirjat",
        "💰 Lompakko",
        "📑 Lisenssi",
        "🌐 Kääntäjä",
        "🤖 Insinööri",
        "🎞 Medialuoja",
        "⚙️ Asetukset",
        "📞 Tuki"
    ],
    "sv": [
        "📖 Instruktion",
        "📊 Budget",
        "📚 Kunskapsbas",
        "🛠 Verktyg",
        "📎 Dokument",
        "💰 Plånbok",
        "📑 Licens",
        "🌐 Översättare",
        "🤖 Ingenjör",
        "🎞 Mediagenerator",
        "⚙️ Inställningar",
        "📞 Support"
    ]
}