repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        args: ["detect", "--no-git", "--source=WebKurierCore"]
        stages: [commit]

  - repo: https://github.com/PyCQA/bandit
    rev: 'stable'
    hooks:
      - id: bandit
        args: ["-r", "WebKurierCore"]
        stages: [commit]