repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        args: ["detect", "--no-git", "--source=."]
        stages: [commit]

  - repo: https://github.com/PyCQA/bandit
    rev: stable
    hooks:
      - id: bandit
        args: ["-r", "./engine", "./multipass", "./handlers"]
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: "\\.(yaml|yml)$"
      - id: check-json
        files: "\\.(json)$"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
        files: "\\.(js|py|sh)$"

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
        exclude: "webqr/|lang-select/"

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        exclude: "webqr/|lang-select/"

  - repo: https://github.com/prettier/prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
        files: "\\.(js|ts|jsx|tsx|json|html|css|md)$"
        exclude: "engine/|handlers/|multipass/"

  - repo: https://github.com/adrienverge/yamllint-precommit
    rev: v0.1.1
    hooks:
      - id: yamllint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        files: "\\.sh$"
        args: ["--severity=style"]

default_stages: [commit, push]
