blank_issues_enabled: false

contact_links:
  - name: "📚 Документация проекта"
    url: "https://github.com/Vladislav6410/webkurier-level8-telegrambot#readme"
    about: "Ознакомься с документацией перед созданием задачи."

  - name: "💬 Вопросы и идеи — Discussions"
    url: "https://github.com/Vladislav6410/webkurier-level8-telegrambot/discussions"
    about: "Если это не баг и не фича — обсудим здесь."

  - name: "🛡️ Сообщить об уязвимости"
    url: "https://github.com/Vladislav6410/webkurier-level8-telegrambot/security/advisories/new"
    about: "Конфиденциально сообщить о проблеме безопасности."

  - name: "🗺️ Дорожная карта / Таскборд"
    url: "https://github.com/Vladislav6410/webkurier-level8-telegrambot/projects"
    about: "Посмотри текущие эпики и прогресс по проекту."